export const types = {
    FETCH_ARTICLE_REQUEST: "FETCH_ARTICLE_REQUEST",
    FETCH_ARTICLE_SUCCESS: "FETCH_ARTICLE_SUCCESS",
    FETCH_ARTICLE_FAILURE: " FETCH_ARTICLE_FAILURE",
    DELETE_ARTICLE_REQUEST: "DELETE_ARTICLE_REQUEST",
    DELETE_ARTICLE_SUCCESS: "DELETE_ARTICLE_SUCCESS",
    DELETE_ARTICLE_FAILURE: "DELETE_ARTICLE_FAILURE",
};
