export const types = {
    FETCH_ARTICLES_REQUEST: "FETCH_ARTICLES_REQUEST",
    FETCH_ARTICLES_SUCCESS: "FETCH_ARTICLES_SUCCESS",
    FETCH_ARTICLES_FAILURE: "FETCH_ARTICLES_FAILURE",
    POST_ARTICLES_REQUEST: "POST_ARTICLES_REQUEST",
    POST_ARTICLES_SUCCESS: "POST_ARTICLES_SUCCESS",
    POST_ARTICLES_FAILURE: "POST_ARTICLES_FAILURE",
};
